### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [rpartap/Colmar-Academy#3]
Alternatively, you could specify these shared properties using comma-separated selectors:

```css
h1, h2, h3 {
  color: white;
  font-family: 'Fira Sans', sans-serif;
}
```

https://github.com/rpartap/Colmar-Academy/blob/master/resources/css/style.css#L31-L47
